import { signOut, getAuth } from "firebase/auth";
import { handleGithubSignOut } from "../../../../src/modules/Users-Authentication/application/signOutWithGithub";
import { mockAuth } from "../../__mocks__/Auth/mockedAuthObject";

jest.mock("firebase/auth", () => ({
  getAuth: jest.fn(),
  signOut: jest.fn(),
}));

jest.mock("../../../../src/firebaseConfig", () => {
  return {
    __esModule: true,
    default: jest.fn(),
  };
});

describe("handleGithubSignOut function", () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it("should sign out successfully", async () => {
    (getAuth as jest.MockedFunction<typeof getAuth>).mockReturnValue(mockAuth);

    (signOut as jest.MockedFunction<typeof signOut>).mockResolvedValue(
      undefined
    );

    await handleGithubSignOut();

    expect(getAuth).toHaveBeenCalledTimes(1);
    expect(signOut).toHaveBeenCalledWith(mockAuth);
  });

  it("should handle sign-out error", async () => {
    const errorMessage = "Sign-out error message";
    (getAuth as jest.MockedFunction<typeof getAuth>).mockReturnValue(mockAuth);

    (signOut as jest.MockedFunction<typeof signOut>).mockRejectedValue(
      new Error(errorMessage)
    );
    const consoleErrorSpy = jest.spyOn(console, "error").mockImplementation();

    await handleGithubSignOut();

    expect(getAuth).toHaveBeenCalledTimes(1);
    expect(signOut).toHaveBeenCalledWith(mockAuth);
    expect(consoleErrorSpy).toHaveBeenCalledWith(
      "Error al cerrar sesi√≥n",
      expect.any(Error)
    );
    expect(consoleErrorSpy.mock.calls[0][1].message).toEqual(errorMessage);

    consoleErrorSpy.mockRestore();
  });
});
